server:
  port: 8082

spring:
  application:
    name: restaurant-service

  datasource:
    url: jdbc:postgresql://postgres-restaurant:5432/restaurant_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        service-name: restaurant-service
        health-check-path: /actuator/health
        health-check-interval: 15s
        prefer-ip-address: true

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      bootstrap-servers: kafka:9092
      group-id: restaurant-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    mk.finki.restaurantservice: DEBUG
